# Generated by Django 4.1.2 on 2022-10-26 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='customemail',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='customfirstname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='customlastname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='customusername',
        ),
    ]
