# Generated by Django 4.1.2 on 2022-10-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainb', '0003_alter_blogpost_author_delete_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='posted',
            field=models.DateField(auto_now=True),
        ),
    ]
