# Generated by Django 4.1.1 on 2022-11-01 20:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainb', '0005_author_alter_blogpost_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainb.author')),
                ('com_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mainb.blogpost')),
            ],
        ),
    ]
