# Generated by Django 4.1.1 on 2022-11-15 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainb', '0006_blogcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
